---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: default
  # TODO: Figure out what's wrong with using IAM Roles for Service Accounts in Spark
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/en1-eksplayground-pod-iam-spark-role

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: spark
  namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io