---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-pod
  template:
    metadata:
      name: hello-world-pod
      labels:
        app: hello-world-pod
    spec:
      containers:
      - name: hello-world
        image: 000000000000.dkr.ecr.eu-north-1.amazonaws.com/eksplayground/hello-world@sha256:f65b99a52fc79d8bf9b9a7061f2db4056a0435fcc5cb054bc4ee6c575421aa6a
        resources:
          requests:
            cpu: 500m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 150Mi

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-world-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
