---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-deployment
    spec:
      containers:
      - name: hello-world
        image: 000000000000.dkr.ecr.eu-north-1.amazonaws.com/eksplayground/hello-world
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: hello-world-deployment
