---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world-pod
  namespace: default
spec:
  containers:
  - name: hello-world
    image: 000000000000.dkr.ecr.eu-north-1.amazonaws.com/eksplayground/hello-world
    resources:
      requests:
        cpu: 500m
        memory: 50Mi
      limits:
        cpu: 1
        memory: 150Mi

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world-pod
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 8080
