AWSTemplateFormatVersion: 2010-09-09
Description: EKS Playground - Resources for log collection

Resources:
  ContainerLogLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
      LogGroupName: !Sub ${AWS::StackName}-container-logs
