---
AWSTemplateFormatVersion: 2010-09-09
Description: EKS Playground - Security Groups for EKS control and data planes

Parameters:
  StackNamePrefix:
    Description: A prefix for the stacks in this setup.
    Type: String

Resources:

  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}-sg
      GroupDescription: !Sub Security Group for EKS Cluster control plane (${AWS::StackName})
      VpcId: !ImportValue infra-vpc-VpcId
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-sg

Outputs:
  ControlPlaneSecurityGroupId:
    Description: Security droup ID of the EKS control plane security group
    Value: !Ref ControlPlaneSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-ControlPlaneSecurityGroupId
