---
AWSTemplateFormatVersion: 2010-09-09
Description: EKS Playground - Node Group

Parameters:
  StackNamePrefix:
    Description: A prefix for the stacks in this setup.
    Type: String

Conditions:
  IsIreland: !Equals [!Ref AWS::Region, eu-west-1]

Resources:

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2_x86_64
      CapacityType: SPOT
      ClusterName: !Sub ${StackNamePrefix}-eks-cluster
      InstanceTypes:
        - !If [IsIreland, m4.large, !Ref AWS::NoValue]
        - !If [IsIreland, m5a.large, !Ref AWS::NoValue]
        - !If [IsIreland, m5ad.large, !Ref AWS::NoValue]
        - m5.large
        - m5d.large
      NodeRole:
        Fn::ImportValue: !Sub ${StackNamePrefix}-base-iam-WorkerNodeInstanceRoleArn
      ScalingConfig:
        DesiredSize: 1
        MinSize: 1
        MaxSize: 4
      Subnets:
        - !ImportValue infra-vpc-sn-nat-a # private
        - !ImportValue infra-vpc-sn-nat-b # private
