---
AWSTemplateFormatVersion: 2010-09-09
Description: EKS Playground - EKS Cluster Control Plane

Parameters:
  StackNamePrefix:
    Description: A prefix for the stacks in this setup.
    Type: String

Resources:
  EKSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/eks/${AWS::StackName}-cluster/cluster
      RetentionInDays: 30
      Tags:
        - { Key: Name, Value: !Sub '/aws/eks/${AWS::StackName}-cluster/cluster' }

  EKSControlPlane:
    Type: AWS::EKS::Cluster
    DependsOn: EKSLogGroup
    Properties:
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: audit
      Name: !Sub ${AWS::StackName}-cluster
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${StackNamePrefix}-base-sg-ControlPlaneSecurityGroupId
        SubnetIds:
          - !ImportValue infra-vpc-sn-nat-a # private
          - !ImportValue infra-vpc-sn-nat-b # private
          - !ImportValue infra-vpc-sn-public-a # public
          - !ImportValue infra-vpc-sn-public-b # public
      RoleArn:
        Fn::ImportValue: !Sub ${StackNamePrefix}-base-iam-EKSServiceRoleArn
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}-cluster' }
      Version: '1.22'

Outputs:
  EKSClusterEndpoint:
    Value: !GetAtt EKSControlPlane.Endpoint
    Export:
      Name: !Sub ${AWS::StackName}-EKSClusterEndpoint
  EKSClusterOIDCIssuerUrl:
    Value: !GetAtt EKSControlPlane.OpenIdConnectIssuerUrl
    Export:
      Name: !Sub ${AWS::StackName}-EKSClusterOIDCIssuerUrl
