AWSTemplateFormatVersion: 2010-09-09
Description: IAM Roles for Pods running in the playground
Parameters:
  StackNamePrefix:
    Description: A prefix for the stacks in this setup.
    Type: String
  OIDCProviderId:
    Description: ID of the OIDC provider created for IRSA.
    Type: String

Resources:
  IrsaTestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Principal": { "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OIDCProviderId}" },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "oidc.eks.eu-north-1.amazonaws.com/id/FC277300AFD9CF2B8ADD849BF13E7D16:sub": "system:serviceaccount:default:irsa-test"
              }
            }
          }]
        }

      RoleName: !Sub ${AWS::StackName}-irsa-test
      Path: /
      Policies:
      - PolicyName: TestAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: TestAccess
            Effect: Allow
            Action:
            - eks:ListClusters
            Resource: '*'
